# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.AddField(
            model_name='tag',
            name='parent',
            field=models.ManyToManyField(related_name='_tag_parent_+', to='core.Tag'),
        ),
    ]
