# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170426_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_tag_parent_+', to='core.Tag'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
