# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170426_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='slug'),
            preserve_default=False,
        ),
    ]
